version: "3"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      DB: database
  database:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - /home/yc-user/data:/data/db